name: 'Trigger Refresh'
description: 'Trigger refresh of the debian repo index in the master branch'
inputs:
  token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ inputs.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/hyprland-debian/hyprland-debian.github.io/actions/workflows/refresh.yml/dispatches \
              -d '{"ref":"master"}'
      shell: bash
